### ISSUE TITLE
Can you make it more secure?

### ISSUE THREAD

**Issue by MKM12345** [hamdivazim/PassSafe#1]
In [this](https://github.com/hamdivazim/PassSafe/blob/41a7f13c66154d4d7a565ab0a08474820642d5a9/PassSafe/PassSafe/PasswordView.swift) file, it's worth noting that it's not recommended to hardcode sensitive information like passwords in your code. Storing passwords in plain text is a security risk, and it's better to use secure storage mechanisms like the keychain or a password manager.

**Comment by hamdivazim** [comment]
Which line number is this? I believe there is no instance of passwords being stored plainly - they are encrypted then stored on Firebase, which also adds a second layer of encryption.
